### PR TITLE
Added support for serial MULTI protocol (serialMode == 5).

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by KnuckleUpFPV** [comment]
How do I use this. I'm sorry for such a new guy question. Im learning as I go. I have wolfbox modules. They are type 3. I would like to test this. I learned how to burn a bootloader to a bad receiver from manufacturer. Its working now. Do i just copy the text and replace it in the arduino ide for openlrsng?

**Comment by mikeller** [comment]
@KnuckleUpFPV: At the moment you'll have to build your own firmware from the tip of master for this. You'll also have to install the configurator from the tip of the repository, to get the combobox entry for MULTIPROTOCOL.

I am planning to release an updated version of firmware and configurator in the near future, as soon as I get around to it. The configurator needs some updates first (mainly preparation for the inevitable demise of the Chrome Web store for non-Chromebooks), so if you can hang on for a couple more weeks, you should be able to update in a more convenient way.

**Comment by KnuckleUpFPV** [comment]
I have no idea how to do any of that. Lol. I appreciate all that you are doing though. Im in no rush. My systems are working fine as is with frsky telemetry. Thanks for all the hard work and time invested. Im really excited to see the outcome.

**Comment by rtbcoop** [comment]
Any update on when this will be available?

And just to confirm, this allows er9x to connect to a openLRSng Tx through serial instead of our normal PPM method? I use the "multiprotocol" option with my IRX4 and would love to be able to do the same for my Hawkeye Tx module.

**Comment by mikeller** [comment]
@rtbcoop: It is available: https://github.com/openLRSng/openLRSng/releases/tag/3.9.0-rc2 . For now, you will have to use a manually installed configurator from the repository, and download the firmware yourself.

But this will be fixed with the next configurator release.

And yes, the Multiprotocol is compatible with the 'normal' Multiprotocol modules.

**Pull request merged**
